### ISSUE TITLE
import error in isolate.py

### ISSUE THREAD

**Issue by rameshvnair** [bhattlab/BacMetSearch#1]
Line 8 in **isolate.py** should import `parse_diamond_search` as well from **diamond.py** as below else will get `NameError: name 'parse_diamond_search' is not defined` error.

`from bacmetsearch.diamond import run_diamond, parse_diamond_search`

**Comment by durrantmm** [comment]
Hi Ramesh!

Thanks for that, I've fixed it.

**Comment by rameshvnair** [comment]
Thanks, Matt. I re-installed this and `bacmetsearch isolate *.fasta` works fine now without the above error.

**Comment by durrantmm** [comment]
Great!
